lowlatency:
  - services/battle_eye.yaml
  - services/cloudflare.yaml
  - services/discord.yaml
  - services/escapefromtarkov.yaml
  - services/google.yaml

generic:
  - services/rcd.yaml

aiservice:
  - services/ai/anthropic.yaml
  - services/ai/gemini.yaml
  - services/ai/openai.yaml
